apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: express-app
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        command: ["/bin/sh"]
        args:
          - -c
          - |
            cat > /usr/share/nginx/html/index.html << 'EOF'
            <!DOCTYPE html>
            <html>
            <head>
                <title>Simple Express.js App</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 40px; }
                    .container { max-width: 600px; margin: 0 auto; }
                    .json { background: #f4f4f4; padding: 20px; border-radius: 5px; }
                    pre { margin: 0; }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>Welcome to Simple Express.js App!</h1>
                    <p>This is your Express.js application running in Kubernetes.</p>
                    
                    <h2>API Response:</h2>
                    <div class="json">
                        <pre>{
                "message": "Welcome to Simple Express.js App!",
                "timestamp": "$(date -Iseconds)",
                "version": "1.0.0",
                "environment": "production",
                "hostname": "$(hostname)"
            }</pre>
                    </div>
                    
                    <h2>Available Endpoints:</h2>
                    <ul>
                        <li><a href="/">/</a> - This page</li>
                        <li><a href="/health">/health</a> - Health check</li>
                        <li><a href="/api/info">/api/info</a> - App information</li>
                        <li><a href="/api/users">/api/users</a> - Sample users</li>
                    </ul>
                </div>
            </body>
            </html>
            EOF
            
            cat > /usr/share/nginx/html/health << 'EOF'
            {
                "status": "healthy",
                "timestamp": "$(date -Iseconds)",
                "uptime": "$(uptime -p)",
                "hostname": "$(hostname)"
            }
            EOF
            
            nginx -g 'daemon off;'
      volumes:
      - name: html-content
        emptyDir: {}