apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  labels:
    app: express-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: express-app
---
apiVersion: v1
kind: Service
metadata:
  name: express-app-clusterip
  labels:
    app: express-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: express-app