apiVersion: v1
kind: Service
metadata:
  name: html-app-service
  labels:
    app: html-app
spec:
  type: NodePort
  selector:
    app: html-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP