apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: html-app-monitor
  namespace: monitoring
  labels:
    app: html-app
spec:
  selector:
    matchLabels:
      app: html-app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 30s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-app-monitor
  namespace: monitoring
  labels:
    app: express-app
spec:
  selector:
    matchLabels:
      app: express-app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 30s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-monitor
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-monitor
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
  - port: http-grafana
    interval: 30s
    path: /metrics